login:
  path: /login
  defaults: { _controller: AppBundle:Usuario:Login}

login_check:
  path: login_check

logout:
  path: /logout  

usuarios_homepage:
  path: /
  defaults: { _controller: AppBundle:Usuario:Principal}

usuario_tesorero:
  path: /administrador
  defaults: {_controller: AppBundle:Usuario:PrincipalTesorero}

usuario_gestion:
  path: /administrador/gestionusuarios
  defaults: {_controller: AppBundle:Usuario:GestionU}
##usaurio_sociob:
##  path: /sociob
##  defaults: {_controller: AppBundle:Usuario:PrincipalSocioB}

##usuario_sociop:
##  path: /sociop
##  defaults: {_controller: AppBundle:Usuario:PrincipalSocioP}
  
##suario_administrador:
##  path: /admin
##  defaults: {_controller: AppBundle:Usuario:PrincipalAdministrador}

usuario_alta:
  path: /administrador/altauduario
  defaults: {_controller: AppBundle:Usuario:FormularioAlta}

usuario_consulta:
  path: /administrador/consultarnombreusuario/{name}
  defaults: {_controller: AppBundle:Usuario:ConsultarUserName}

usuario_consultae:
  path: /administrador/consultaremail/{correo}
  defaults: {_controller: AppBundle:Usuario:ConsultarEmail}

usuario_consultadni:
  path: /administrador/consultardocumento/{dni}
  defaults: {_controller: AppBundle:Usuario:ConsultarDni}

operacion_registro:
  path: /administrador/registraroperaciones/{usn}
  defaults: {_controller: AppBundle:Operacion:FormularioOperacion}

operacion_reporte:
  path: /administrador/reporte
  defaults: {_controller: AppBundle:Operacion:ReportePDF}