login:
  path: /login
  defaults: { _controller: AppBundle:Usuario:Login}

login_check:
  path: login_check

logout:
  path: /logout  

usuarios_homepage:
  path: /
  defaults: { _controller: AppBundle:Usuario:Principal}

usuario_tesorero:
  path: /administrador
  defaults: {_controller: AppBundle:Usuario:PrincipalTesorero}

usuario_principala:
  path: /administrador/inicio
  defaults: {_controller: AppBundle:Usuario:PrincipalA}

usuario_principalu:
  path: /usuario/inicio
  defaults: {_controller: AppBundle:Usuario:PrincipalU}

usuario_gestion:
  path: /administrador/gestionususuarios
  defaults: {_controller: AppBundle:Usuario:GestionU}

usuario_listar:
  path: /administrador/listarusuarios
  defaults: {_controller: AppBundle:Usuario:ListarU}  

usuario_editardatos:
  path: /administrador/editardatosusuario/{id}
  defaults: {_controller: AppBundle:Usuario:EditarDatos} 

usuario_update:
  path: /admin/actualizardatos/{id}
  defaults: {_controller: AppBundle:Usuario:ActualizarDatos}

usuario_updatePass:
  path: /admin/restablecercontraseña/{id}
  defaults: {_controller: AppBundle:Usuario:ModificarPasword}

usuario_editarpass:
  path: /administrador/editarpassusuario/{id}
  defaults: {_controller: AppBundle:Usuario:EditarPass} 

usuario_editCcorreo:
  path: /administrador/edit/consultaremail/{correo}/{id}
  defaults: {_controller: AppBundle:Usuario:ConsultarEditEmail}

usuario_editCdni:
  path: /administrador/editar/consultardocumento/{dni}/{id}
  defaults: {_controller: AppBundle:Usuario:ConsultarEditDni}

usuario_alta:
  path: /administrador/altauduario
  defaults: {_controller: AppBundle:Usuario:FormularioAlta}

usuario_consulta:
  path: /administrador/consultarnombreusuario/{name}
  defaults: {_controller: AppBundle:Usuario:ConsultarUserName}

usuario_consultae:
  path: /administrador/consultaremail/{correo}
  defaults: {_controller: AppBundle:Usuario:ConsultarEmail}

usuario_consultadni:
  path: /administrador/consultardocumento/{dni}
  defaults: {_controller: AppBundle:Usuario:ConsultarDni}

operacion_registro:
  path: /administrador/registraroperaciones/{usn}
  defaults: {_controller: AppBundle:Operacion:FormularioOperacion}

operacion_reporte:
  path: /administrador/reporte
  defaults: {_controller: AppBundle:Operacion:ReportePDF}

##operacion_prueba:
##  path: /administrador/reporteprueba/{name}
##  defaults: {_controller: AppBundle:Operacion:hello}


##_pdf_using_facade_directly:
##  path: /administrador/reporteprueba
##  defaults: { _controller: AppBundle:Operacion:Reporte }

reporte_generara:
  path: /administrador/reporteporfecha
  defaults: { _controller: AppBundle:Operacion:RepoInicio}  

operacion_Reportexf:
  path: /administrador/consulta
  defaults: {_controller: AppBundle:Operacion:ConsultarOperaciones}

ver_xml:
  path: /administrador/verxml
  defaults: { _controller: AppBundle:Operacion:VerXml}  

###########################################################
######################rutas usuario########################
###########################################################
operacion_registrou:
  path: /usuario/registraroperaciones/{usn}
  defaults: {_controller: AppBundle:Operacion:FormularioOperacion}

##_pdf_using_facade_directlyu:
##  path: /usuario/reporteprueba
##  defaults: { _controller: AppBundle:Operacion:Reporte }

reporte_generaru:
  path: /usuario/reporteporfecha
  defaults: { _controller: AppBundle:Operacion:RepoInicio}

operacion_Reportexfu:
  path: /usuario/consulta
  defaults: {_controller: AppBundle:Operacion:ConsultarOperaciones}